//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libarary_Management_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENDINGPAYMENT
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> LastpaymentDate { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
